# Generated by Django 5.0 on 2025-04-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_feedback_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'feedback'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
