# Generated by Django 5.0 on 2025-04-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
