# Generated by Django 5.0 on 2025-05-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
