# Generated by Django 5.0 on 2025-04-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='user_profile_pic/'),
        ),
    ]
