# Generated by Django 5.0 on 2025-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/user_profile_pictures/fallback.png', upload_to='user_profile_pictures/'),
        ),
    ]
